### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by gustavoandrade10** [clovesmjunior/printJS#1]
Acrescentar logo no header

**Comment by clovesmjunior** [comment]
Hey Gustavo,

Looks like to add tag "image" in "pageHeader" to solved your problem. For example:

`pageHeader:{	  			
				image:{
					image64: "data:image/jpeg;base64,"+codeBase64,
					formatImage: "JPEG" (opcional),
					x: (opcional),
					y: (opcional),
					w: (opcional),
					h: (opcional)
				}
	  		}`
